### ISSUE TITLE
Panel plugin not found: timeseries

### ISSUE THREAD

**Issue by xuexiaoao** [vesoft-inc/nebula-stats-exporter#15]
[https://github.com/vesoft-inc/nebula-stats-exporter/blob/master/deploy/grafana/bare-metal/nebula-grafana.json](url)

使用这个grafana配置，报如下错：

![image](https://user-images.githubusercontent.com/18185523/114684024-1bd14000-9d43-11eb-8c26-a8b1047508d3.png)

**Comment by liduang** [comment]
我也是显示没有这个插件，去grafana.com也没找到这个插件
![image](https://user-images.githubusercontent.com/37337756/115188888-2d865f00-a118-11eb-85d0-445c7b77d742.png)

**Comment by MegaByte875** [comment]
The  dashboard was exported from docker grafana（v7.5.2）, I will check it.  Please tell me the grafana version that you used @xuexiaoao @liduang

**Comment by xuexiaoao** [comment]
The version used is v7.3.7 (1e261642f4)

**Comment by MegaByte875** [comment]
> The version used is v7.3.7 (1e261642f4)

okey, I will check it under  v7.3.7

**Comment by MegaByte875** [comment]
@xuexiaoao   Hi,  you can test it with pr [17](https://github.com/vesoft-inc/nebula-stats-exporter/pull/17)，I configure it with grafana v7.3.7
