### ISSUE TITLE
KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

### ISSUE THREAD

**Issue by boomballa** [vesoft-inc/nebula-stats-exporter#33]
我想直接指定配置文件启动服务，没想容器部署，为什么一定要制定KUBERNETES_SERVICE_HOST 和 KUBERNETES_SERVICE_PORT呢？

shell:~/nebula-stats-exporter$ ./nebula-stats-exporter --bare-metal-config="/nebula-stats-exporter/config.yaml"
F0818 16:56:51.941470   40432 main.go:63] build config failed: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

**Comment by MegaByte875** [comment]
You should specify the baremental environment with --bare-metal parameter.
./nebula-stats-exporter --bare-metal --bare-metal-config="/nebula-stats-exporter/config.yaml"
