### ISSUE TITLE
nebula-stats-exporter 自定义端口不生效【建议优化】

### ISSUE THREAD

**Issue by VincentSleepless** [vesoft-inc/nebula-stats-exporter#9]
docker 镜像启动nebula-stats-exporter和prometheus, 在修改端口和配置文件启动的情况下，镜像仍然会占用和使用默认端口

 docker run -d --restart=always -p 9200:9200 -v /opt/nebula-stats-exporter/deploy/bare-metal:/config \
>  vesoft/nebula-stats-exporter:v0.0.2  --bare-metal --bare-metal-config-path=/config/config.yaml

docker run -d --name=prometheus --restart=always -p 9080:9080 -v /opt/nebula-stats-exporter/deploy/bare-metal/prometheus.yml prom/prometheus

[root@data-cdh-d1-01 bare-metal]#
[root@data-cdh-d1-01 bare-metal]# docker logs d08aed79e558
I1230 10:35:08.504653       1 exporter.go:317] Begin Describe Nebula Metrics
I1230 10:35:08.507006       1 exporter.go:330] Describe Nebula Metrics Done
I1230 10:35:08.508366       1 main.go:81] Providing metrics at :9100/metrics
[root@data-cdh-d1-01 bare-metal]#

修改端口原因，阿里云esc会默认拉起一个进程监听9100端口，不使用自定义端口则监控无法使用.

希望可以支持

**Comment by MegaByte875** [comment]
You can add parameter --listen-address to modify exporter listen port.  Thank you for your feedback. I will continue to improve the documentation instructions.
